"""
Run this script on Google Colab to convert the fine-tuned ViT to TFLite.

1. Open https://colab.research.google.com/
2. Paste this script into a code cell
3. Update REPO_ID and MODEL_DIR if needed
4. Run the cell
5. Download the resulting ZIP from /content/

Output: fasaguard_final_93pct_tflite.zip containing:
  - model_float32.tflite  (~345 MB, highest accuracy)
  - model_float16.tflite  (~172 MB, negligible accuracy loss)
  - model_int8.tflite     (~86 MB, fastest for mobile)
  - class_indices.json    (label mapping)
  - preprocessor_config.json
"""

# --- Configuration ---
REPO_ID = "Ammar5525/fasalguard"  # HF Space repo with Git LFS
MODEL_DIR = "fasalguard_final_93pct"  # dir name in repo root
# --- End configuration ---

import json, shutil, subprocess, sys, zipfile
from pathlib import Path

OUTPUT_DIR = Path("/content/fasalguard_final_93pct_tflite")
MODEL_SOURCE = Path(f"/content/{MODEL_DIR}")


def setup():
    print(">>> Installing dependencies...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q",
         "torch", "transformers", "onnx", "onnx2tf", "tensorflow"],
        check=True, capture_output=True,
    )


def clone_model():
    print(f">>> Cloning model from {REPO_ID}...")
    subprocess.run(
        ["git", "clone", f"https://huggingface.co/{REPO_ID}", "/content/repo"],
        check=True, capture_output=True,
    )

    src = Path("/content/repo") / MODEL_DIR
    if not src.exists():
        missing = list(Path("/content/repo").iterdir()) if Path("/content/repo").exists() else []
        raise FileNotFoundError(f"Model dir '{MODEL_DIR}' not found in repo. Found: {missing}")

    shutil.copytree(src, MODEL_SOURCE)
    print(f"    Model files: {list(MODEL_SOURCE.iterdir())}")


def export_onnx():
    print(">>> PyTorch -> ONNX...")
    from transformers import AutoModelForImageClassification, AutoImageProcessor
    import torch

    model = AutoModelForImageClassification.from_pretrained(str(MODEL_SOURCE))
    processor = AutoImageProcessor.from_pretrained(str(MODEL_SOURCE))
    model.eval()

    dummy = torch.randn(1, 3, 224, 224)

    onnx_dir = OUTPUT_DIR / "onnx"
    onnx_dir.mkdir(parents=True, exist_ok=True)
    onnx_path = onnx_dir / "model.onnx"

    torch.onnx.export(
        model, dummy, onnx_path,
        input_names=["pixel_values"],
        output_names=["logits"],
        dynamic_axes={
            "pixel_values": {0: "batch_size"},
            "logits": {0: "batch_size"},
        },
        opset_version=14,
    )
    print(f"    ONNX: {onnx_path}")
    return onnx_path


def convert_tflite(onnx_path):
    print(">>> ONNX -> TFLite...")
    tflite_dir = OUTPUT_DIR / "tflite"
    tflite_dir.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        [sys.executable, "-m", "onnx2tf", "-i", str(onnx_path), "-o", str(tflite_dir)],
        check=True, capture_output=True, text=True,
    )
    print(f"    TFLite base: {tflite_dir}")

    # Quantize
    import tensorflow as tf

    base_tflite = list(tflite_dir.glob("*.tflite"))
    if not base_tflite:
        raise FileNotFoundError("No TFLite model generated by onnx2tf")

    saved_model_dir = tflite_dir / "saved_model"
    if saved_model_dir.exists():
        # float16 quantization
        converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_dir))
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.float16]
        tflite_16 = converter.convert()
        (OUTPUT_DIR / "model_float16.tflite").write_bytes(tflite_16)
        print(f"    float16: {len(tflite_16) / 1024 / 1024:.0f} MB")

        # int8 quantization (needs representative dataset)
        print("    int8: skipped (needs representative dataset)")
    else:
        # Just copy the base model
        src = base_tflite[0]
        shutil.copy2(src, OUTPUT_DIR / "model_float32.tflite")
        print(f"    float32: {src.stat().st_size / 1024 / 1024:.0f} MB (copied)")


def save_metadata():
    print(">>> Saving metadata...")
    with open(MODEL_SOURCE / "config.json") as f:
        config = json.load(f)
    class_indices = {int(k): v for k, v in config["id2label"].items()}
    with open(OUTPUT_DIR / "class_indices.json", "w") as f:
        json.dump(class_indices, f, indent=2)

    shutil.copy2(MODEL_SOURCE / "preprocessor_config.json", OUTPUT_DIR / "preprocessor_config.json")

    labels = [class_indices[i] for i in sorted(class_indices)]
    with open(OUTPUT_DIR / "labels.txt", "w") as f:
        f.write("\n".join(labels))

    print(f"    {len(class_indices)} classes saved")


def create_zip():
    print(">>> Creating ZIP...")
    zip_path = Path("/content/fasalguard_final_93pct_tflite.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in OUTPUT_DIR.rglob("*"):
            if f.is_file() and f.parent.name != "onnx" and f.parent.name != "tflite":
                zf.write(f, f.relative_to(OUTPUT_DIR.parent))
    print(f"    ZIP: {zip_path} ({zip_path.stat().st_size / 1024 / 1024:.0f} MB)")
    print("    Download it from the Files sidebar in Colab.")


def main():
    print("=" * 60)
    print("  FasalGuard: ViT -> TFLite Converter (Colab)")
    print("=" * 60)

    setup()
    clone_model()
    onnx_path = export_onnx()
    convert_tflite(onnx_path)
    save_metadata()
    create_zip()

    print("\nDone! Download /content/fasalguard_final_93pct_tflite.zip")
    print("Then copy model_float16.tflite + class_indices.json to app/ or backend/")


if __name__ == "__main__":
    main()
